name: Release new version

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582

      - name: Build with Gradle Wrapper
        run: |
          cd perviam
          chmod +x gradlew
          ./gradlew createExe shadowJar distZip --no-daemon

      - name: Move artifacts
        run: |
          mkdir out
          mv ./perviam/build/distributions/Perviam-*.zip out/
          cp ./perviam/build/libs/perviam.jar out/
          cd ./perviam/build/launch4j && zip -r ../../../out/perviam-windows.zip .

      - name: Release binaries
        uses: softprops/action-gh-release@v2
        with:
          name: Perviam-${{ github.ref_name }}
          files: out/*
          fail_on_unmatched_files: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Temurin Alpine
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            astarivi/perviam:${{ github.ref_name }}-temurin-alpine
            astarivi/perviam:${{ github.ref_name }}-temurin
            astarivi/perviam:latest
          build-args: |
            BASE_IMAGE=eclipse-temurin:21-jre-alpine

      - name: Build Temurin Ubuntu
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            astarivi/perviam:${{ github.ref_name }}-temurin-noble
          build-args: |
            BASE_IMAGE=eclipse-temurin:21-jre-noble

      - name: Create Docker README
        run: |
          sed 's/{ver}/${{ github.ref_name }}/g' docker/README.template.md > docker/README.md

      - name: Sync Docker README.md
        uses: meeDamian/sync-readme@70e38f5bc63205951219b8e02afb1d6c1f57fa0a
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_PASS }}
          slug: astarivi/perviam
          readme: ./docker/README.md
          description: "Perviam: a movement based reverse geocoder"